services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "4444:80"
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /run
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
